import json
import sys
from typing import Any, Dict

import requests


def main() -> None:
    url: str = "http://localhost:8001/predict"
    payload: Dict[str, Any] = {
        "data": [
            {
                "id": 1,
#                "text": "Здравствуйте!В августе оформила карту unionpay в городе Москва для вылета в Дубаи!Сотрудник все быстро и чётко объяснил про акцию возврата стоимости за изготовление карты в размере 5 тыс рублей при выполнении условий - 3 мес трат на сумму 10 тыс рублей, либо не снимать определённую сумму рублей. Я тратила в сентябре, октябре и ноябре необходимую сумму, при том, что звонила (а это в нынешних реалиях темпа жизни по 30 минут дозвона!!!!В чатах не отвечают!!!Могу приложить скрины!!!Пишут что ответит оператор и его имя, но никто не отвечает!Якобы большая нагрузка по обращениям - ещё бы!это вообще вопиюще по 25-30 минут на связи висеть и потом ещё может сброситься звонок!), в общем операторы проверяли мои расходы, потому что оказывается в условиях не все \"коды\" проходили и например коммуналка или покупки через маркетплейсы не считались! По условиям я читала что кэшбэк должен был вернуться на 20 рабочий день, но этого не случилось, потом я позвонила и оператор проверив выполнения условия озвучил, что в последний день месяца ждите - это 31.12, но и в этот день ничего не пришло, потом я зашла на банки.ру и увидела, что \"обман\" такой имеет место быть...очень неожиданно конечно, что банк может себе такое позволить. Прошу разобраться в сложившейся ситуации и помочь вернуть сумму кэшбэка.",
                 "text": "Решили с мужем открыть накопительные счета в Газпромбанке. Перевела по СБП (по своему номеру телефона) из другого банка сумму на свою карту ГПБ. Зачислили, вопросов нет! Далее делаю перевод мужу на карту ГПБ по номеру КАРТЫ. Выдаёт лимит на операцию. Ок - уменьшаю сумму перевода до лимита, перевожу. Перевод прошёл. Пытаюсь перевести мужу остаток - операция отклонена, подозрение на мошенничество. Получается первая сумма прошла нормально (ну мошенники и мошенники, Бог с ними), а вторая часть уже не прошла. В ДРУГИХ банках - банк сразу же звонит клиенту- здесь пришло сообщение чтоб Я позвонила в банк. Звоню - 15 минут ожидания на линии. Пытаюсь снова перевести деньги мужу (по номеру телефона, по номеру карты - отклоняет). Ок, думаю, верну обратно себе же деньги по номеру телефона на ТОТ ЖЕ банк, откуда они пришли 15 минут назад. Не дает - подозрение на мошенничество. А ничего что согласно законодательству я могу перечислять сама себе в разные банки до 30 млн руб в месяц без комиссий и лимитов. Ок пытаюсь кинуть по СБП на свой же счет в ТБанк - снова отказ. Ну и дбо заблокировалось вместе с моими деньгами. Звоню на горячую линию - 17 минут ожидания - терпеливо жду. Потом 40 минут разговора с сотрудником - решение - идите в банк с паспортом для РАЗБЛОКИРОВКИ своего дбо. Те остальные банки сами звонят при подозрении на мошенничество, спрашивают кодовые слова (а ГПБ зачем вообще тогда мое кодовое слово), Банк даже звонит по видео, чтобы убедиться что Я это я, а вот вам решение от ГПБ в век высоких технологий- отпросись с работы и езжай в офис, просиди в очереди 1,5 часа и докажи, что ты это ты. А до этого момента твои деньги будут тупо лежать на карте (а не накоп счёте), без процентов! ГПБ, может уже стоит выйти из \"советской' эпохи - 21 век на дворе. Самый прикол - я не смогла доехать до офиса для открытия счета (они работают до 19, как и я), но карту мне любезно привез курьер. НО чтобы и дальше пользоваться услугами онлайн - добро пожаловать ЛИЧНО в офис! Спасибо, никаких накопительных счетов мне от вас не нужно - нервы себе дороже!",
            }
        ]
    }

    try:
        response = requests.post(url, json=payload, timeout=30)
        response.raise_for_status()
    except requests.RequestException as exc:
        print(f"HTTP error: {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        data = response.json()
    except ValueError:
        print("Invalid JSON in response", file=sys.stderr)
        print(response.text)
        sys.exit(1)

    print(json.dumps(data, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()


